apiVersion: v1

kind: ReplicationController

metadata:
  name: firstreplicationcontroller
  #  name: secondreplicationcontroller
  labels:
    appname: voatingapp


spec:
  replicas: 5
  template:
    metadata:
      name: firstpod
      labels:
       type: app
    spec:
      containers:
        - image: coolgourav147/nginx-custom:v1
          name: firtcontainer
