apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: development
  name: deployment-manager-binding
subjects:
  - kind: User
    name: Gulab
    apiGroup: ""
roleRef:
  apiGroup: ""
  kind: Role
  name: deployment-manager
